/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SubReddit_subreddit.graphql
 * @generated SignedSource<<4828529718422afe8f8e7778e9558a23>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type SubReddit_subreddit = {
  name: string;
  posts?: ?SubReddit_subreddit_posts;
};

export type SubReddit_subreddit_posts_edges = {
  node: any;
};

export type SubReddit_subreddit_posts = {
  edges?: ?Array<?SubReddit_subreddit_posts_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "SubReddit_subreddit",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "PostConnection",
      "name": "posts",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PostEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Post",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "FragmentSpread",
                  "name": "Post_item",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "SubReddit"
};

module.exports = fragment;
