/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Post_item.graphql
 * @generated SignedSource<<344cfbede0728e9b8040d6b05f6010d0>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Post_item = {
  title: string;
  url?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Post_item",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "title",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "url",
      "storageKey": null
    }
  ],
  "type": "Post"
};

module.exports = fragment;
